###
POST http://localhost:8080/coupon/new 
content-type: application/json

{
    "name": "test2",
    "maxUse": 5,
    "country": "PL"
}

###
GET http://localhost:8080/ 

###
PUT http://localhost:8080/coupon/use/test12
content-type: application/json

{
    "userId": "abc"
}
